(async () => {
    const assert = (value, message) => { if (!value) throw Error(message); };
    const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
    switchMode('play');
    window.showGameTutorial = () => {};
    document.getElementById('in-game-tutorial')?.remove();
    isGamePaused = false;
    aiPet.schedule = []; aiPet.isReincarnating = false; aiPet.age = 0; aiPet.lifespan = 10000;
    aiPet.apprentice = { learnedWords: ['hello'], rank: { building: 10 }, retired: { building: true } };
    const home = (x) => ({ type: 'hut', dx: x, dy: 150, sw: 90, sh: 90, scale: .5, name: '小屋' });
    assets.residentTestHome = home(220); assets.residentTestHut = home(350);
    Residents.ensure(aiPet, assets);
    const previous = JSON.parse(JSON.stringify(aiPet)); previous.name = '<img src=x onerror=alert(1)>';
    const next = Residents.prepareSuccession(previous, { ...previous, generation: previous.generation + 1 }, { map: true }, 'browser-life');
    Object.assign(aiPet, next); aiPet.isReincarnating = false;
    Residents.ensure(aiPet, assets);
    const house = Object.values(assets).find(a => Residents.isResidentHome(aiPet, a, assets));
    assert(house, 'resident hut exists');
    Residents.assignHome(aiPet, assets, previous.personId, house.instanceId, 2);
    ResidentUI.roster(); await wait(100);
    assert(document.querySelector('.resident-card h3').textContent.includes('<img'), 'literal name rendered');
    assert(!document.querySelector('.resident-card img'), 'name cannot create markup');
    const modal = document.querySelector('.resident-overlay'); modal.querySelector('header button').click();
    assert(!GameShell.isPaused(), 'roster releases only its pause');
    openResidentHomeUI(house); await wait(100);
    assert(GameShell.currentScene === 'resident-home', 'central resident scene');
    assert(document.querySelector('#resident-home-ui .myhome-character'), 'resident and hero sprites');
    assert(document.querySelectorAll('#resident-home-ui [data-sprite-key="hfur_bed"]').length === 4, 'four fixed beds');
    aiPet.getMaxVocabulary = () => 100;
    GameShell.routeChat('resident vocabulary');
    assert(aiPet.apprentice.learnedWords.includes('resident vocabulary'), 'resident home learning');
    assert(document.querySelector('.resident-learning-bubble')?.textContent.includes('resident vocabulary'), 'resident home learning speech');
    const actor = aiPet.residentState.people[previous.personId];
    actor.location = { kind: 'island', x: 410, y: 210 }; actor.activity = { phase: 'walk', elapsed: 0, path: [{ x: 450, y: 210 }] };
    renderResidentHome();
    const before = actor.location.x;
    const pause = GameShell.acquirePause('resident-test');
    for (let i = 0; i < 30; i++) ResidentUI.tick(50);
    assert(actor.location.x === before, 'pause freezes residents');
    GameShell.releasePause(pause);
    ResidentUI.tick(50); assert(actor.location.x > before, 'resident movement resumes');
    const heroPosition = { x: aiPet.x, y: aiPet.y };
    GameShell.routeChat('でる');
    for (let i = 0; i < 60; i++) ResidentUI.tick(50);
    assert(GameShell.currentScene === 'island', 'walk out of resident house');
    assert(aiPet.x === heroPosition.x && aiPet.y === heroPosition.y, 'restore island origin');
    saveGameData();
    const saved = JSON.parse(localStorage.getItem('ai_pet_data_v1'));
    assert(saved.residentState.people[previous.personId].home.slot === 2, 'fixed slot is persisted');
    ResidentUI.roster();
    return { residentId: previous.personId, housed: true, escapedName: true, pauseAndWalk: true };
})();
