const assert = require('node:assert/strict');
const C = require('../schedule_core.js');
const start = new Date(2026, 8, 14, 0).getTime();
const hero = () => ({ personId: 'test', energy: 100, hunger: 100, stats: { intel: 10, power: 10, speed: 10, beauty: 10, mood: 100 }, inventory: [] });
const context = { items: (a, s) => a[s], food: () => ({ stats: { hunger: 30 } }), efficiency: () => 1 };
function plan(action, end = 1440) { const p = C.empty(); p.enabled = true; p.days = p.days.map(() => [{ start: 0, end, action }]); return p; }
assert.throws(() => C.validate(plan('invalid')));
const overlap = plan('study'); overlap.days[0].push({ start: 60, end: 80, action: 'rest' }); assert.throws(() => C.validate(overlap));
assert.equal(C.timeline(plan('study', 30), 0)[1].action, 'blank');
const a = hero(), b = hero(), p = plan('study');
C.simulateActor(a, p, start, start + 60000, context, []);
for (let t = start; t < start + 60000; t += 50) C.simulateActor(b, p, t, t + 50, context, []);
assert(Math.abs(a.stats.intel - b.stats.intel) < 1e-8, 'visible and offline same growth');
assert(Math.abs(a.energy - b.energy) < 1e-8, 'visible and offline same consumption');
const exhausted = hero(); exhausted.energy = 5; const events = [];
C.simulateActor(exhausted, p, start, start + 3600000, context, events);
assert.equal(events.length, 1); assert.equal(exhausted.stats.intel, 10); assert.equal(exhausted.energy, 5);
const meal = plan('eat'); meal.days.forEach(d => d[0].meal = { sources: ['inventory'], itemId: 'food' });
const hungry = hero(); hungry.hunger = 20; hungry.inventory = ['food', 'food'];
C.simulateActor(hungry, meal, start, start + 60000, context, []);
C.simulateActor(hungry, meal, start + 60000, start + 120000, context, []);
assert.equal(hungry.inventory.length, 1, 'one meal once per occurrence, including reload');
const waiting = hero(); C.simulateActor(waiting, C.empty(), start, start + 86400000, context, []); assert.equal(waiting.stats.intel, 10);
const immediate = [{ type: 'study', duration: 10 }]; const queuedActor = hero();
C.simulateActor(queuedActor, plan('rest'), start, start + 20000, context, [], immediate);
assert.equal(immediate.length, 0); assert.equal(queuedActor.stats.intel, 11);
const travel = hero();
C.simulateActor(travel, p, start, start + 10000, { ...context, route: () => ({ position: { x: 0, y: 0 }, path: [{ x: 350, y: 0 }], destination: { x: 350, y: 0 } }) }, []);
assert.equal(travel.x, 350); assert.equal(travel.stats.intel, 10, 'travel has nonzero duration');
const forecast = C.forecast(hero(), p, context, start); assert.equal(forecast.failure.status, 'resources');
assert.equal(C.forecast(hero(), plan('rest'), context, start).stable, true);
console.log('Schedule core: validation, gaps, partition invariance, meals, exhaustion, queue, travel, forecast passed.');
const gathering = plan('gather'); const g1 = hero(), g2 = hero();
const unitContext = { ...context, unit: (a, slot, action, seed, at) => { a.inventory.push({ id: String(seed), at }); return String(seed); } };
C.simulateActor(g1, gathering, start, start + 60000, unitContext, []);
for (let at = start; at < start + 60000; at += 1000) C.simulateActor(g2, gathering, at, at + 1000, unitContext, []);
assert.deepEqual(g1.inventory, g2.inventory, 'offline units have identical drops and timestamps');
