const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const C = require('../schedule_core');
require('../resident_core');
const Residents = globalThis.Residents;
const start = new Date(2026, 8, 14, 0).getTime();
const listeners = {};
let now = start, saves = 0, failAt = Infinity;
const storage = new Map();
const localStorage = { getItem: k => storage.get(k) || null, setItem: (k, v) => { if (++saves === failAt) throw Error('disk full'); storage.set(k, v); } };
globalThis.localStorage = localStorage;
const hero = { personId: 'hero', generation: 1, currentSkin: 'robot', age: 1, lifespan: 100, energy: 100, hunger: 100, stats: { intel: 10 }, inventory: [], schedule: [], lastSaveTime: start,
    setDestination(x, y) { this.pathQueue = [{ x, y }]; return true; }, getTraitData() { return {}; } };
const map = {};
Residents.ensure(hero, map);
const ctx = { console, Date: class extends Date { static now() { return now; } }, assets: map, itemCatalog: { food: { type: 'food', stats: { hunger: 30 } } }, document: { hidden: false, addEventListener(k, v) { listeners[k] = v; } },
    window: { ScheduleCore: C, Residents, aiPet: hero, GameShell: { currentScene: 'island', suspendPauseClock() {} }, addEventListener(k, v) { listeners[k] = v; } } };
vm.createContext(ctx); vm.runInContext(fs.readFileSync('schedule_runtime.js', 'utf8'), ctx);
const R = ctx.window.ScheduleRuntime;
const plan = C.empty(); plan.enabled = true; plan.days = plan.days.map(() => [{ start: 0, end: 1440, action: 'study', destination: 'current' }]);
hero.routine = plan;
now += 60000; R.settle(now);
assert.equal(hero.stats.intel, 16); assert.equal(hero.energy, 94);
R.settle(now); assert.equal(hero.stats.intel, 16, 'same interval cannot replay');
const first = C.clone(hero);
now += 60000;
// prepared save: commit point plus map and cleanup writes; fail the result commit.
failAt = saves + 4;
assert.throws(() => R.settle(now), /disk full/);
assert.equal(hero.stats.intel, first.stats.intel, 'failed result is not applied live');
assert(hero.timeProgress.pending);
failAt = Infinity;
R.settle(now);
assert.equal(hero.stats.intel, 22, 'saved result recovers once');
assert(!hero.timeProgress.pending);
assert.equal(hero.timeProgress.report.before[hero.personId].stats.intel, 10, 'unread reports retain original baseline');
const dead = C.clone(hero); dead.age = 99; dead.lifespan = 100; dead.lifeAgeTimer = 86380;
dead.residentState.people = { resident: { personId: 'resident', home: { buildingId: 'h', slot: 0 }, location: { kind: 'island', x: 0, y: 0 }, profile: { energy: 100, hunger: 100, stats: { intel: 10 } }, possessions: { inventory: [], freezer: [], equipment: {} }, routine: plan } };
const deathReport = R.simulate(dead, {}, now, now + 86400000, true);
assert.equal(deathReport.deathAt, now + 1000);
assert(Math.abs(dead.residentState.people.resident.profile.stats.intel - 10.1) < 1e-8, 'all resident progress stops at death');
assert.equal(dead.age, 100);
const noPlan = C.clone(hero); delete noPlan.routine; noPlan.age = 1; noPlan.lifeAgeTimer = 0;
R.simulate(noPlan, {}, now, now + C.config.ageUnitMs, true);
assert.equal(noPlan.age, 2); assert.equal(noPlan.stats.intel, hero.stats.intel, 'age advances without unplanned growth');
hero.timeProgress.report.acknowledged = true;
R.boot();
ctx.document.hidden = true; listeners.visibilitychange(); const checkpoint = hero.timeProgress.checkpoint;
now += 30000; assert.equal(R.tick(now), false); assert.equal(hero.timeProgress.checkpoint, checkpoint);
ctx.document.hidden = false; listeners.visibilitychange();
assert.equal(hero.timeProgress.checkpoint, now);
console.log('Schedule runtime: exact-once settlement, failed commit recovery, unread reports, global death boundary, passive age and visibility passed.');
ctx.itemCatalog.item_medicine_cure = { type: 'medicine' };
ctx.itemCatalog.elixir = { type: 'medicine' };
const medicineCase = id => {
    const value = C.clone(hero);
    value.age = 99; value.lifespan = 100; value.lifeAgeTimer = 86380;
    value.inventory = [id]; value.schedule = [{ type: 'eat', targetItem: id, duration: 1 }, { type: 'study', duration: 5 }];
    value.conditions = { cold: true }; value.isSick = true; value.energy = 100; value.hunger = 100;
    delete value.routineState; delete value.timeProgress;
    return value;
};
const cured = medicineCase('item_medicine_cure'), curedIntel = cured.stats.intel;
const cureReport = R.simulate(cured, {}, now, now + 10000, true);
assert.equal(cureReport.deathAt, now, 'life-shortening medicine takes effect at consumption, before the next action');
assert.equal(cured.lifespan, 95); assert.equal(cured.stats.intel, curedIntel);
assert.equal(cured.inventory.length, 0); assert.equal(cured.isSick, false);
const extended = medicineCase('elixir');
const extendedReport = R.simulate(extended, {}, now, now + 10000, true);
assert.equal(extended.lifespan, 110); assert.equal(extendedReport.deathAt, undefined, 'elixir extends the previously calculated death deadline');
assert(extended.stats.intel > curedIntel);
const interactive = medicineCase('elixir'); interactive.schedule = [{ type: 'study', duration: .5 }, { type: 'apprentice_exam', duration: 300 }];
interactive.isSick = false;
const stopped = R.simulate(interactive, {}, now, now + 10000, true);
assert.equal(stopped.deathAt, now + 1000, 'aging continues after reaching an interactive queued action');
assert.equal(interactive.schedule[0].duration, 300, 'interactive work is retained');
console.log('Schedule medicine: consumption-time death, lifespan extension and interactive aging passed.');
