const fs = require('fs');
const path = require('path');
const {
    ROOT,
    localeFile,
    readJson
} = require('./catalog_shared');

const locales = ['en', 'zh-CN', 'ru', 'es-ES', 'pt-BR', 'de'];
const catalogs = {};
for (const locale of locales) catalogs[locale] = readJson(localeFile(locale), {});

const output = `/* Generated by npm run i18n:build. Do not edit directly. */\nwindow.GAME_I18N_CATALOGS = ${JSON.stringify(catalogs)};\n`;
fs.writeFileSync(path.join(ROOT, 'localization_catalog.js'), output, 'utf8');
process.stdout.write(`Built localization_catalog.js for ${locales.length} translated languages.\n`);
