'use strict';
// Both the visible preview and smoke run use disposable profiles, never player storage.
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
if (!process.versions.electron || process.type !== 'browser') {
    const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
    const child = require('node:child_process').spawn(require('electron'), [__filename, ...process.argv.slice(2)], { env, stdio: 'inherit', windowsHide: true });
    child.on('exit', code => { process.exitCode = code || 0; });
} else {
    const { app, BrowserWindow } = require('electron');
    const assert = require('node:assert/strict');
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'word-diary-preview-'));
    app.setPath('userData', directory); app.disableHardwareAcceleration();
    const smoke = process.argv.includes('--smoke');
    let server;
    app.whenReady().then(async () => {
        server = require('./serve').createServer();
        await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
        const window = new BrowserWindow({ width: 1000, height: 900, show: !smoke, autoHideMenuBar: true,
            webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
        window.setMenu(null); window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
        const errors = [];
        window.webContents.on('console-message', (_event, level, message) => { if (level >= 3) errors.push(message); });
        const url = `http://127.0.0.1:${server.address().port}/experimental_word_diary.html`;
        await window.loadURL(url);
        if (!smoke) { console.log(`Independent diary sample: ${url}`); return; }
        const js = async code => {
            try { return await window.webContents.executeJavaScript(code, true); }
            catch (error) { throw new Error(`${error.message}\nRenderer code: ${code}\nConsole: ${JSON.stringify(errors)}`); }
        };
        const settle = () => js('document.fonts.ready.then(() => new Promise(resolve => setTimeout(resolve, 180)))');
        window.webContents.debugger.attach('1.3');
        await window.webContents.debugger.sendCommand('DOM.enable');
        await window.webContents.debugger.sendCommand('CSS.enable');
        await settle();
        await js(`localStorage.setItem('preview-sentinel','keep'); sessionStorage.setItem('preview-sentinel','keep'); void 0`);
        // Exercise the independent clock in the real renderer only during smoke.
        // It is intentionally absent from both preview HTML and game HTML.
        const clockSource = fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_clock.js'), 'utf8');
        await js(clockSource);
        const clockResult = await js(`(() => {
            const clock = ExperimentalWordDiaryClock;
            const partial = { dayIndex: 0, elapsedMs: clock.DAY_MS - 100 };
            const stopped = clock.STOP_REASONS.map(reason => clock.advance(partial, 86400000, { [reason]: true }));
            const overlapping = clock.advance(partial, 200, { manualPaused: true, encounterOpen: false });
            const sleep = clock.advance(partial, 200);
            const resumed = clock.advance(JSON.parse(JSON.stringify(partial)), 50);
            delete globalThis.ExperimentalWordDiaryClock;
            return { stopped, overlapping, sleep, resumed, partial };
        })()`);
        const partial = { dayIndex: 0, elapsedMs: 1499900 };
        for (const stopped of clockResult.stopped) assert.deepEqual(stopped, { state:partial, crossedDays:0 });
        assert.deepEqual(clockResult.overlapping, { state:partial, crossedDays:0 });
        assert.deepEqual(clockResult.sleep, { state:{ dayIndex:1, elapsedMs:100 }, crossedDays:1 });
        assert.deepEqual(clockResult.resumed, { state:{ dayIndex:0, elapsedMs:1499950 }, crossedDays:0 });
        assert.deepEqual(clockResult.partial, partial);
        // The candidate buffer is also injected only for this isolated test.
        // Supplied snapshots are fixtures, not records generated by a living actor.
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        const candidateResult = await js(`(() => {
            const buffer = ExperimentalWordDiaryCandidates.create();
            const fixture = { occurrenceId: 0, kind: 'experience', sourceId: 0,
                captured: { target: 'berry:1', taste: 'sweet', known: [] } };
            const first = buffer.retain(fixture);
            fixture.captured.known.push('sweet');
            const repeated = buffer.retain(fixture);
            buffer.read()[0].captured.known.push('eat');
            buffer.retain({ occurrenceId: 1, kind: 'teaching', sourceId: 'input:1', captured: {} });
            buffer.retain({ occurrenceId: 2, kind: 'question', sourceId: 'input:2', captured: {} });
            const entries = buffer.read();
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { first, repeated, entries, removed: typeof ExperimentalWordDiaryCandidates };
        })()`);
        assert.equal(candidateResult.first, true);
        assert.equal(candidateResult.repeated, false);
        assert.equal(candidateResult.entries.length, 3);
        assert.deepEqual(candidateResult.entries[0], { occurrenceId:0, kind:'experience', sourceId:0,
            captured:{ target:'berry:1', taste:'sweet', known:[] } });
        assert.deepEqual(candidateResult.entries.map(item => item.kind), ['experience', 'teaching', 'question']);
        assert.equal(candidateResult.removed, 'undefined');
        // Actual parser/reply results from disposable Node state. Only the
        // question adapter and buffer enter the renderer, never the game world.
        const core = require('../../experimental_word_learning_core');
        const worldApi = require('../../experimental_word_learning_world');
        const wordCatalog = require('../../experimental_word_learning_catalog.json');
        const questionInput = '\u3069\u3046\u3057\u3066\u4f11\u3093\u3060\u306e\uff1f';
        const makeQuestion = (options = {}, text = questionInput) => {
            const state = core.create(options, wordCatalog);
            const result = core.receive(state, text, wordCatalog, { at: 100 });
            return { result, reply: worldApi.respond(worldApi.create(), result, state) };
        };
        const questionFixtures = [makeQuestion(), makeQuestion({ speech: 'gesture' }),
            makeQuestion({ foundation: false, life: false }), makeQuestion({}, 'unsupported input')];
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_questions.js'), 'utf8'));
        const questionResult = await js(`(() => {
            const fixtures = ${JSON.stringify(questionFixtures)};
            const buffer = ExperimentalWordDiaryCandidates.create();
            const accepted = fixtures.map(value => ExperimentalWordDiaryQuestions.capture(buffer, value.result, value.reply));
            const original = buffer.read();
            fixtures[0].result.understandings.at(-1).known.meaning = 'sweet';
            const repeated = ExperimentalWordDiaryQuestions.capture(buffer, fixtures[0].result, fixtures[0].reply);
            buffer.read()[0].captured.answer = 'found';
            const entries = buffer.read();
            delete globalThis.ExperimentalWordDiaryQuestions;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { accepted, original, repeated, entries,
                removed: [typeof ExperimentalWordDiaryQuestions, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        assert.deepEqual(questionResult.accepted, [true, false, false, false]);
        assert.equal(questionResult.repeated, false);
        assert.deepEqual(questionResult.entries, questionResult.original);
        assert.equal(questionResult.entries[0].captured.raw, questionInput);
        assert.deepEqual(questionResult.entries[0].captured.understanding, questionFixtures[0].result.understandings.at(-1));
        assert.equal(questionResult.entries[0].sourceId, questionFixtures[0].result.input.id);
        assert.deepEqual(questionResult.removed, ['undefined', 'undefined']);
        // Naming results come from disposable Node state. The renderer gets
        // copied input/attention/understanding only, with no actor or save bridge.
        const makeNameState = (options = {}, attention = [{ id:'berry:1', meaning:'berry' }]) => {
            const state = core.create(options, wordCatalog);
            core.perceive(state, { scene:'clearing', attention });
            return state;
        };
        const hearName = (state, raw = '\u3053\u308c\u3092\u300c\u3053\u308d\u300d\u3068\u547c\u3076\u3088') => {
            const context = JSON.parse(JSON.stringify({ scene:state.context.scene, attention:state.context.attention }));
            return { context, result:core.receive(state, raw, wordCatalog, { at:100 + state.serial }) };
        };
        const hearDefinition = (state, raw, locale = 'ja', speaker = 'player') => {
            const context = JSON.parse(JSON.stringify({ scene:state.context.scene, attention:state.context.attention }));
            const beforeKnowledge = JSON.parse(JSON.stringify(state.knowledge));
            return { context, beforeKnowledge, result:core.receive(state, raw, wordCatalog, { locale, speaker, at:100 + state.serial }) };
        };
        const makeLabelState = (activity = 'eat', options = {}) => {
            const state = core.create({ life:false, ...options }, wordCatalog), world = worldApi.create();
            Object.assign(world, { mode:activity, attention:activity === 'eat' ? 'berry:1' : 'shade',
                elapsed:1, activityStart:1, dwell:.1, harvest:1, hunger:.8, fatigue:.7,
                activityBefore:{ hunger:.8, fatigue:.7 } });
            if (activity === 'eat') world.mealTaste = { quality:'sweet', pleasant:true };
            return { state, world };
        };
        const hearLabel = (value, raw, locale = 'ja', speaker = 'player') => {
            const context = JSON.parse(JSON.stringify({ ...value.world, scene:value.state.context.scene }));
            const beforeKnowledge = JSON.parse(JSON.stringify(value.state.knowledge));
            const result = core.receive(value.state, raw, wordCatalog, { locale, speaker, at:100 + value.state.serial });
            worldApi.respond(value.world, result, value.state);
            return { context, beforeKnowledge, result };
        };
        // Unknown explanation-relation teaching: real receive/respond in Node
        // memory, copied acceptance-time material only in the renderer.
        const makeRelationState = (activity = 'rest', options = {}) => {
            const value = makeLabelState(activity, { foundation:false, life:true, ...options });
            core.perceive(value.state, { scene:'clearing', attention:[{ id:value.world.attention,
                meaning:activity === 'eat' ? 'berry' : 'rest' }] });
            return value;
        };
        const hearRelation = (value, raw, locale = 'ja', speaker = 'player') => {
            const { state, world } = value;
            const context = JSON.parse(JSON.stringify({ scene:state.context.scene, attention:state.context.attention,
                mode:world.mode, target:world.attention, activityStart:world.activityStart, elapsed:world.elapsed }));
            const beforeKnowledge = JSON.parse(JSON.stringify(state.knowledge));
            const result = core.receive(state, raw, wordCatalog, { locale, speaker, at:100 + state.serial });
            worldApi.respond(world, result, state, wordCatalog);
            return { context, beforeKnowledge, result };
        };
        const relationFixtures = [];
        for (const [locale, forms] of Object.entries(wordCatalog.correctionTeaching)) {
            for (const foundation of [false, true]) for (const life of [false, true]) for (const speech of ['short', 'gesture']) {
                for (const activity of ['eat', 'rest']) {
                    const raw = activity === 'rest' ? forms.exampleSource : forms.exampleReplacement.replace(/^.*?[.\u3002]\s*/u, '');
                    relationFixtures.push({ values:[hearRelation(makeRelationState(activity, { foundation, life, speech }), raw, locale)],
                        expected:[!foundation && life] });
                }
            }
        }
        const relationText = wordCatalog.correctionTeaching.ja.exampleSource;
        const repeatedRelationState = makeRelationState();
        relationFixtures.push({ values:[hearRelation(repeatedRelationState, relationText), hearRelation(repeatedRelationState, relationText),
            hearRelation(repeatedRelationState, relationText.replace(/\u307d\u307d/u, 'ruru'))], expected:[true, true, true] });
        assert.equal(repeatedRelationState.world.relationLabels.length, 1);
        const completedRelationState = makeRelationState(), originalRelation = hearRelation(completedRelationState, relationText);
        completedRelationState.world.pause = 0;
        worldApi.onArrival(completedRelationState.world, completedRelationState.state, worldApi.tick(completedRelationState.world, .1));
        Object.assign(completedRelationState.world, { mode:'eat', attention:'berry:1', activityStart:completedRelationState.world.elapsed,
            dwell:.1, harvest:1, mealTaste:{ quality:'sweet', pleasant:true }, activityBefore:{ hunger:.8, fatigue:completedRelationState.world.fatigue } });
        core.perceive(completedRelationState.state, { scene:'clearing', attention:[{ id:'berry:1', meaning:'berry' }] });
        const secondRelation = hearRelation(completedRelationState,
            wordCatalog.correctionTeaching.ja.exampleReplacement.replace(/^.*?[.\u3002]\s*/u, '').replace(/\u307d\u307d/u, 'mogu'));
        completedRelationState.world.pause = 0;
        worldApi.onArrival(completedRelationState.world, completedRelationState.state, worldApi.tick(completedRelationState.world, .1));
        assert.ok(completedRelationState.state.knowledge.relations.some(r => r.id === 'naming' && r.source === 'experienced_relation'));
        assert.equal((completedRelationState.state.knowledge.wordExplanations || []).length, 0);
        relationFixtures.push({ values:[originalRelation, secondRelation], expected:[true, true] });
        const interruptedRelationState = makeRelationState(), interruptedRelation = hearRelation(interruptedRelationState, relationText);
        interruptedRelationState.world.mode = 'observe'; interruptedRelationState.world.relationLabels = [];
        relationFixtures.push({ values:[interruptedRelation], expected:[true] });
        relationFixtures.push({ values:[hearRelation(makeRelationState('eat'), relationText)], expected:[false] });
        relationFixtures.push({ values:[hearRelation(makeRelationState(), relationText, 'ja', 'visitor')], expected:[false] });
        const ambiguousRelationState = makeRelationState();
        ambiguousRelationState.state.context.attention.push({ id:'berry:1', meaning:'berry' });
        relationFixtures.push({ values:[hearRelation(ambiguousRelationState, relationText)], expected:[false] });
        const missingRelation = JSON.parse(JSON.stringify(originalRelation)); missingRelation.beforeKnowledge.meanings = [];
        relationFixtures.push({ values:[missingRelation], expected:[false] });
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_relation_labels.js'), 'utf8'));
        const relationResult = await js(`(() => {
            const fixtures = ${JSON.stringify(relationFixtures)};
            const results = fixtures.map(fixture => {
                const buffer = ExperimentalWordDiaryCandidates.create(), source = JSON.stringify(fixture);
                const capture = value => ExperimentalWordDiaryRelationLabels.capture(buffer, value.result, value.context, value.beforeKnowledge);
                const accepted = fixture.values.map(capture), original = buffer.read();
                const sourcePreserved = source === JSON.stringify(fixture), repeated = fixture.values.map(capture);
                if (original.length) { buffer.read()[0].captured.sources.input.raw = 'changed';
                    fixture.values[0].beforeKnowledge.meanings.push({ id:'later', source:'initial' }); }
                return { accepted, repeated, original, entries:buffer.read(), sourcePreserved };
            });
            delete globalThis.ExperimentalWordDiaryRelationLabels;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { results, removed:[typeof ExperimentalWordDiaryRelationLabels, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        for (const [index, result] of relationResult.results.entries()) {
            assert.deepEqual(result.accepted, relationFixtures[index].expected, `relation teaching ${index}`);
            assert.ok(result.repeated.every(value => value === false));
            assert.equal(result.sourcePreserved, true); assert.deepEqual(result.entries, result.original);
            for (const entry of result.entries) {
                assert.equal(entry.captured.understanding.complete, false);
                assert.deepEqual(entry.captured.understanding.unresolved, [{ type:'relation', id:'naming' }]);
                assert.equal(entry.captured.pairing.candidates[0].inputId, entry.sourceId);
            }
        }
        assert.deepEqual(relationResult.removed, ['undefined', 'undefined']);
        // 3b1 examples: acceptance-time copies, not an actual child answer.
        const exampleForms = {
            ja:['\u4f55\u3057\u3066\u308b\uff1f','\u98df\u3079\u308b','\u4f11\u3080'], en:['What are you doing?','eat','rest'],
            'zh-CN':['你在做什么？','吃','休息'], ru:['Что ты делаешь?','есть','отдых'],
            'es-ES':['¿Qué estás haciendo?','comer','descansar'],
            'pt-BR':['O que você está fazendo?','comer','descansar'], de:['Was machst du?','speisen','ausruhen']
        };
        const exampleText = (locale = 'ja', activity = 'rest') => `「${exampleForms[locale][0]}」→「${exampleForms[locale][activity === 'eat' ? 1 : 2]}」`;
        const exampleFixtures = [];
        for (const locale of Object.keys(exampleForms)) for (const foundation of [false,true])
            for (const life of [false,true]) for (const speech of ['short','gesture']) for (const activity of ['eat','rest']) {
                const value = makeRelationState(activity, { foundation,life,speech });
                const heard = hearRelation(value, exampleText(locale,activity), locale);
                assert.equal(value.state.context.turns.at(-1).answer, undefined);
                exampleFixtures.push({ values:[heard], expected:[!foundation && life] });
            }
        const repeatedExampleState = makeRelationState();
        exampleFixtures.push({ values:[hearRelation(repeatedExampleState,exampleText()),
            hearRelation(repeatedExampleState,exampleText())], expected:[true,true] });
        assert.equal(repeatedExampleState.world.relationLabels.length,1);
        const completedExampleState = makeRelationState(), firstExample = hearRelation(completedExampleState,exampleText());
        completedExampleState.world.pause = 0;
        worldApi.onArrival(completedExampleState.world,completedExampleState.state,worldApi.tick(completedExampleState.world,.1));
        Object.assign(completedExampleState.world,{ mode:'eat', attention:'berry:1', activityStart:completedExampleState.world.elapsed,
            dwell:.1,harvest:1,mealTaste:{quality:'sweet',pleasant:true},activityBefore:{hunger:.8,fatigue:completedExampleState.world.fatigue} });
        core.perceive(completedExampleState.state,{scene:'clearing',attention:[{id:'berry:1',meaning:'berry'}]});
        const secondExample = hearRelation(completedExampleState,exampleText('ja','eat'));
        completedExampleState.world.pause = 0;
        worldApi.onArrival(completedExampleState.world,completedExampleState.state,worldApi.tick(completedExampleState.world,.1));
        assert.ok(completedExampleState.state.knowledge.relations.some(r=>r.id==='question' && r.source==='experienced_relation'));
        exampleFixtures.push({values:[firstExample,secondExample,hearRelation(completedExampleState,exampleText('ja','eat'))],expected:[true,true,false]});
        const interruptedExampleState = makeRelationState(), interruptedExample = hearRelation(interruptedExampleState,exampleText());
        worldApi.approach(interruptedExampleState.world,'path');
        assert.deepEqual(interruptedExampleState.world.relationLabels,[]);
        exampleFixtures.push({values:[interruptedExample],expected:[true]});
        exampleFixtures.push({values:[hearRelation(makeRelationState('eat'),exampleText())],expected:[false]});
        exampleFixtures.push({values:[hearRelation(makeRelationState(),exampleText(),'ja','visitor')],expected:[false]});
        const ambiguousExampleState = makeRelationState();
        ambiguousExampleState.state.context.attention.push({id:'berry:1',meaning:'berry'});
        exampleFixtures.push({values:[hearRelation(ambiguousExampleState,exampleText())],expected:[false]});
        const missingExample = JSON.parse(JSON.stringify(firstExample)); missingExample.beforeKnowledge.meanings=[];
        exampleFixtures.push({values:[missingExample],expected:[false]});
        const actualAnswerExample = JSON.parse(JSON.stringify(firstExample)); actualAnswerExample.result.relationLearning.candidates[0].roles.actualAnswer=true;
        exampleFixtures.push({values:[actualAnswerExample],expected:[false]});
        exampleFixtures.push({values:[hearRelation(makeRelationState(),exampleForms.ja[0])],expected:[false]});
        await js(fs.readFileSync(path.resolve(__dirname,'../../experimental_word_diary_candidates.js'),'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname,'../../experimental_word_diary_question_examples.js'),'utf8'));
        const exampleResult = await js(`(() => {
            const fixtures=${JSON.stringify(exampleFixtures)};
            const results=fixtures.map(fixture=>{
                const buffer=ExperimentalWordDiaryCandidates.create(),source=JSON.stringify(fixture);
                const capture=value=>ExperimentalWordDiaryQuestionExamples.capture(buffer,value.result,value.context,value.beforeKnowledge);
                const accepted=fixture.values.map(capture),original=buffer.read();
                const sourcePreserved=source===JSON.stringify(fixture),repeated=fixture.values.map(capture);
                if(original.length) { buffer.read()[0].captured.pairing.candidates[0].roles.actualAnswer=true;
                    fixture.values[0].beforeKnowledge.meanings.push({id:'later',source:'initial'}); }
                return {accepted,repeated,original,entries:buffer.read(),sourcePreserved};
            });
            delete globalThis.ExperimentalWordDiaryQuestionExamples;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return {results,removed:[typeof ExperimentalWordDiaryQuestionExamples,typeof ExperimentalWordDiaryCandidates]};
        })()`);
        for (const [index,result] of exampleResult.results.entries()) {
            assert.deepEqual(result.accepted,exampleFixtures[index].expected,`question example ${index}`);
            assert.ok(result.repeated.every(value=>value===false));
            assert.equal(result.sourcePreserved,true); assert.deepEqual(result.entries,result.original);
            for (const entry of result.entries) {
                assert.equal(entry.kind,'teaching');
                assert.deepEqual(entry.captured.understanding.unresolved,[{type:'relation',id:'question'}]);
                assert.equal(entry.captured.pairing.candidates[0].roles.actualAnswer,false);
                assert.equal(entry.captured.pairing.candidates[0].inputId,entry.sourceId);
            }
        }
        assert.deepEqual(exampleResult.results[112].entries.map(e=>e.captured.pairing.adopted.inputId),['input:1','input:1']);
        assert.deepEqual(exampleResult.removed,['undefined','undefined']);
        // Known examples have no relationLearning label or new personal answer.
        const knownExampleFixtures = [];
        for (const locale of Object.keys(exampleForms)) for (const foundation of [false,true])
            for (const life of [false,true]) for (const speech of ['short','gesture']) for (const activity of ['eat','rest']) {
                knownExampleFixtures.push({values:[hearRelation(makeRelationState(activity,{foundation,life,speech}),
                    exampleText(locale,activity),locale)],expected:[foundation && life]});
            }
        const startKnownActivity = (value, activity) => {
            Object.assign(value.world,{mode:activity,attention:activity==='eat'?'berry:1':'shade',
                activityStart:value.world.elapsed,dwell:.1,harvest:1,hunger:.8,fatigue:.7,
                activityBefore:{hunger:.8,fatigue:.7},mealTaste:{quality:'sweet',pleasant:true}});
            core.perceive(value.state,{scene:'clearing',attention:[{id:value.world.attention,meaning:activity==='eat'?'berry':'rest'}]});
        };
        const finishKnownActivity = value => {
            value.world.pause=0; worldApi.onArrival(value.world,value.state,worldApi.tick(value.world,.1));
        };
        for (const locale of Object.keys(exampleForms)) for (const speech of ['short','gesture']) {
            const value=makeRelationState('rest',{speech});
            hearRelation(value,exampleText(locale),locale); finishKnownActivity(value); startKnownActivity(value,'eat');
            hearRelation(value,exampleText(locale,'eat'),locale); finishKnownActivity(value);
            assert.ok(value.state.knowledge.relations.some(r=>r.id==='question' && r.source==='experienced_relation'));
            for (const activity of ['eat','rest']) {
                startKnownActivity(value,activity);
                knownExampleFixtures.push({values:[hearRelation(value,exampleText(locale,activity),locale)],expected:[true]});
            }
        }
        const knownRepeatedState=makeRelationState('rest',{foundation:true});
        const knownFirst=hearRelation(knownRepeatedState,exampleText());
        knownExampleFixtures.push({values:[knownFirst,hearRelation(knownRepeatedState,exampleText())],expected:[true,true]});
        assert.deepEqual(knownRepeatedState.state.records,[]);
        assert.equal(knownRepeatedState.state.context.turns.at(-1).answer,undefined);
        finishKnownActivity(knownRepeatedState); startKnownActivity(knownRepeatedState,'rest');
        worldApi.approach(knownRepeatedState.world,'path');
        knownExampleFixtures.push({values:[knownFirst],expected:[true]});
        knownExampleFixtures.push({values:[firstExample],expected:[false]});
        knownExampleFixtures.push({values:[hearRelation(makeRelationState('eat',{foundation:true}),exampleText())],expected:[false]});
        knownExampleFixtures.push({values:[hearRelation(makeRelationState('rest',{foundation:true}),exampleText(),'ja','visitor')],expected:[false]});
        const knownAmbiguous=makeRelationState('rest',{foundation:true});
        knownAmbiguous.state.context.attention.push({id:'berry:1',meaning:'berry'});
        knownExampleFixtures.push({values:[hearRelation(knownAmbiguous,exampleText())],expected:[false]});
        const knownMissing=JSON.parse(JSON.stringify(knownFirst)); knownMissing.beforeKnowledge.relations=[];
        knownExampleFixtures.push({values:[knownMissing],expected:[false]});
        const knownScoped=JSON.parse(JSON.stringify(knownExampleFixtures[112].values[0]));
        knownScoped.beforeKnowledge.relations.find(r=>r.id==='question').scope.speaker='visitor';
        knownExampleFixtures.push({values:[knownScoped],expected:[false]});
        knownExampleFixtures.push({values:[hearRelation(makeRelationState('rest',{foundation:true}),exampleForms.ja[0])],expected:[false]});
        await js(fs.readFileSync(path.resolve(__dirname,'../../experimental_word_diary_candidates.js'),'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname,'../../experimental_word_diary_known_question_examples.js'),'utf8'));
        const knownExampleResult=await js(`(() => {
            const fixtures=${JSON.stringify(knownExampleFixtures)};
            const results=fixtures.map(fixture=>{
                const buffer=ExperimentalWordDiaryCandidates.create(),source=JSON.stringify(fixture);
                const capture=value=>ExperimentalWordDiaryKnownQuestionExamples.capture(buffer,value.result,value.context,value.beforeKnowledge);
                const accepted=fixture.values.map(capture),original=buffer.read();
                const sourcePreserved=source===JSON.stringify(fixture),repeated=fixture.values.map(capture);
                if(original.length) { buffer.read()[0].captured.roles.actualAnswer=true;
                    fixture.values[0].beforeKnowledge.relations=[]; fixture.values[0].result.input.raw='changed'; }
                return {accepted,repeated,original,entries:buffer.read(),sourcePreserved};
            });
            delete globalThis.ExperimentalWordDiaryKnownQuestionExamples;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return {results,removed:[typeof ExperimentalWordDiaryKnownQuestionExamples,typeof ExperimentalWordDiaryCandidates]};
        })()`);
        for(const [index,result] of knownExampleResult.results.entries()) {
            assert.deepEqual(result.accepted,knownExampleFixtures[index].expected,`known question example ${index}`);
            assert.ok(result.repeated.every(value=>value===false)); assert.equal(result.sourcePreserved,true);
            assert.deepEqual(result.entries,result.original);
            for(const entry of result.entries) {
                assert.equal(entry.kind,'teaching'); assert.equal(entry.captured.understanding.complete,true);
                assert.equal(entry.captured.roles.actualAnswer,false); assert.equal(entry.captured.roles.answerer,'self');
                assert.equal(entry.captured.sources.input.id,entry.sourceId);
                assert.ok(entry.captured.relationBasis.length);
            }
        }
        assert.deepEqual(knownExampleResult.results[140].entries.map(e=>e.sourceId),['input:1','input:2']);
        assert.deepEqual(knownExampleResult.removed,['undefined','undefined']);
        // 3b2 unknown relations: the marked proposal remains source material.
        const proposalText = (kind = 'request', locale = 'ja') => {
            const form = wordCatalog.proposalTeaching[locale][kind];
            return form.marker + '「' + form.utterance + '」';
        };
        const proposalFixtures = [];
        for (const locale of Object.keys(wordCatalog.proposalTeaching)) for (const foundation of [false,true])
            for (const life of [false,true]) for (const speech of ['short','gesture']) for (const kind of ['request','invitation']) {
                proposalFixtures.push({values:[hearRelation(makeRelationState('rest',{foundation,life,speech}),
                    proposalText(kind,locale),locale)],expected:[!foundation && life]});
            }
        for (const kind of ['request','invitation']) {
            const value=makeRelationState(), first=hearRelation(value,proposalText(kind));
            const second=hearRelation(value,proposalText(kind));
            const mixed=hearRelation(value,proposalText(kind==='request'?'invitation':'request'));
            assert.equal(value.world.relationLabels.length,1); assert.equal(mixed.result.relationLearning,undefined);
            proposalFixtures.push({values:[first,second,mixed],expected:[true,true,false]});
        }
        for (const locale of Object.keys(wordCatalog.proposalTeaching)) for (const speech of ['short','gesture']) {
            const value=makeRelationState('rest',{speech});
            const first=hearRelation(value,proposalText('request',locale),locale);
            finishKnownActivity(value); startKnownActivity(value,'rest');
            const second=hearRelation(value,proposalText('invitation',locale),locale);
            finishKnownActivity(value); startKnownActivity(value,'rest');
            for (const kind of ['request','invitation'])
                assert.ok(value.state.knowledge.relations.some(r=>r.id===kind && r.source==='experienced_relation'));
            assert.ok(value.state.experiences.every(e=>e.relationLabels.every(l=>l.roles.actualParticipation===false)));
            proposalFixtures.push({values:[first,second,hearRelation(value,proposalText('request',locale),locale),
                hearRelation(value,proposalText('invitation',locale),locale)],expected:[true,true,false,false]});
        }
        const interruptedProposal=makeRelationState(), proposalFirst=hearRelation(interruptedProposal,proposalText());
        worldApi.approach(interruptedProposal.world,'path');
        assert.deepEqual(interruptedProposal.world.relationLabels,[]);
        assert.equal((interruptedProposal.state.experiences||[]).length,0);
        proposalFixtures.push({values:[proposalFirst],expected:[true]});
        proposalFixtures.push({values:[hearRelation(makeRelationState('eat'),proposalText())],expected:[false]});
        proposalFixtures.push({values:[hearRelation(makeRelationState(),proposalText(),'ja','visitor')],expected:[false]});
        const ambiguousProposal=makeRelationState(); ambiguousProposal.state.context.attention.push({id:'berry:1',meaning:'berry'});
        proposalFixtures.push({values:[hearRelation(ambiguousProposal,proposalText())],expected:[false]});
        for (const mutate of [v=>{v.beforeKnowledge.meanings=[];}, v=>{v.context.scene='other';},
            v=>{v.context.activityStart=2;}, v=>{v.result.relationLearning.candidates[0].inputId='input:99';},
            v=>{v.result.relationLearning.candidates[0].roles.actualParticipation=true;},
            v=>{v.result.relationLearning.adopted.roles.actors=['player'];}]) {
            const invalid=JSON.parse(JSON.stringify(proposalFirst)); mutate(invalid);
            proposalFixtures.push({values:[invalid],expected:[false]});
        }
        for (const raw of [wordCatalog.proposalTeaching.ja.request.utterance,wordCatalog.proposalTeaching.ja.invitation.utterance,
            exampleText(),relationText,proposalText()+'。甘い'])
            proposalFixtures.push({values:[hearRelation(makeRelationState(),raw)],expected:[false]});
        await js(fs.readFileSync(path.resolve(__dirname,'../../experimental_word_diary_candidates.js'),'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname,'../../experimental_word_diary_proposal_examples.js'),'utf8'));
        const proposalResult=await js(`(() => {
            const fixtures=${JSON.stringify(proposalFixtures)};
            const results=fixtures.map(fixture=>{
                const buffer=ExperimentalWordDiaryCandidates.create(),source=JSON.stringify(fixture);
                const capture=value=>ExperimentalWordDiaryProposalExamples.capture(buffer,value.result,value.context,value.beforeKnowledge);
                const accepted=fixture.values.map(capture),original=buffer.read();
                const sourcePreserved=source===JSON.stringify(fixture),repeated=fixture.values.map(capture);
                if(original.length) { buffer.read()[0].captured.sources.frame.roles.actualParticipation=true;
                    fixture.values[0].beforeKnowledge.relations=[]; fixture.values[0].result.input.raw='changed'; }
                return {accepted,repeated,original,entries:buffer.read(),sourcePreserved};
            });
            delete globalThis.ExperimentalWordDiaryProposalExamples;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return {results,removed:[typeof ExperimentalWordDiaryProposalExamples,typeof ExperimentalWordDiaryCandidates]};
        })()`);
        for (const [index,result] of proposalResult.results.entries()) {
            assert.deepEqual(result.accepted,proposalFixtures[index].expected,'proposal example '+index);
            assert.ok(result.repeated.every(value=>value===false)); assert.equal(result.sourcePreserved,true);
            assert.deepEqual(result.entries,result.original);
            for (const entry of result.entries) {
                const label=entry.captured.pairing.candidates[0];
                assert.equal(entry.kind,'teaching'); assert.equal(entry.captured.understanding.complete,false);
                assert.deepEqual(entry.captured.understanding.unresolved,[{type:'relation',id:label.relation}]);
                assert.equal(entry.captured.understanding.roles,undefined);
                assert.equal(label.roles.actualParticipation,false); assert.equal(label.roles.status,'proposed');
                assert.equal(label.inputId,entry.sourceId); assert.equal(label.raw,entry.captured.sources.input.raw);
                assert.deepEqual(entry.captured.sources.frame.roles,label.roles);
            }
        }
        for (const index of [112,113]) {
            assert.deepEqual(proposalResult.results[index].entries.map(e=>e.sourceId),['input:1','input:2']);
            assert.deepEqual(proposalResult.results[index].entries.map(e=>e.captured.pairing.adopted.inputId),['input:1','input:1']);
        }
        assert.deepEqual(proposalResult.removed,['undefined','undefined']);
        const labelFixtures = [];
        for (const [index, locale] of ['ja', 'en', 'zh-CN', 'ru', 'es-ES', 'pt-BR', 'de'].entries()) {
            for (const foundation of [false, true]) for (const life of [false, true]) for (const speech of ['short', 'gesture']) {
                labelFixtures.push({ values:[hearLabel(makeLabelState('eat', { foundation, life, speech }),
                    wordCatalog.meanings.sweet[index], locale)], expected:[true], statuses:[life ? 'recognized' : 'unrecognized'] });
            }
        }
        for (const meaning of ['berry', 'food', 'eat', 'sweet', 'hungry', 'rest', 'sleep', 'tired']) {
            const raw = wordCatalog.meanings[meaning][0];
            labelFixtures.push({ values:[hearLabel(makeLabelState(['rest', 'sleep', 'tired'].includes(meaning) ? 'rest' : 'eat'),
                ['hungry', 'tired'].includes(meaning) ? `"${raw}"` : raw)], expected:[true], statuses:['unrecognized'] });
        }
        const repeatedLabelState = makeLabelState();
        labelFixtures.push({ values:[hearLabel(repeatedLabelState, wordCatalog.meanings.sweet[0]),
            hearLabel(repeatedLabelState, wordCatalog.meanings.sweet[0])], expected:[true, true], statuses:['unrecognized', 'unrecognized'] });
        assert.equal(repeatedLabelState.world.lifeLabels.length, 1);
        const completedLabelState = makeLabelState(), originalLabel = hearLabel(completedLabelState, wordCatalog.meanings.sweet[0]);
        completedLabelState.world.pause = 0;
        worldApi.onArrival(completedLabelState.world, completedLabelState.state, worldApi.tick(completedLabelState.world, .1));
        assert.ok(completedLabelState.state.knowledge.meanings.some(item => item.id === 'sweet'));
        labelFixtures.push({ values:[originalLabel], expected:[true], statuses:['unrecognized'] });
        for (const [raw, locale, speaker] of [[wordCatalog.meanings.food.at(-1), 'de', 'player'],
            [wordCatalog.meanings.sweet[0] + '?', 'ja', 'player'], [wordCatalog.meanings.sweet[0], 'ja', 'visitor']]) {
            labelFixtures.push({ values:[hearLabel(makeLabelState(), raw, locale, speaker)], expected:[false], statuses:[] });
        }
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_life_learning.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_life_labels.js'), 'utf8'));
        const labelResult = await js(`(() => {
            const fixtures = ${JSON.stringify(labelFixtures)};
            const results = fixtures.map(fixture => {
                const buffer = ExperimentalWordDiaryCandidates.create(), source = JSON.stringify(fixture);
                const capture = value => ExperimentalWordDiaryLifeLabels.capture(buffer, value.result, value.context, value.beforeKnowledge);
                const accepted = fixture.values.map(capture), original = buffer.read();
                const sourcePreserved = source === JSON.stringify(fixture);
                const repeated = fixture.values.map(capture);
                if (original.length) { buffer.read()[0].captured.sources.input.raw = 'changed';
                    fixture.values[0].beforeKnowledge.meanings.push({ id:'later', source:'initial' }); }
                return { accepted, repeated, original, entries:buffer.read(), sourcePreserved };
            });
            delete globalThis.ExperimentalWordDiaryLifeLabels;
            delete globalThis.ExperimentalWordLifeLearning;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { results, removed:[typeof ExperimentalWordDiaryLifeLabels, typeof ExperimentalWordLifeLearning, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        for (const [index, result] of labelResult.results.entries()) {
            assert.deepEqual(result.accepted, labelFixtures[index].expected);
            assert.ok(result.repeated.every(value => value === false));
            assert.equal(result.sourcePreserved, true); assert.deepEqual(result.entries, result.original);
            assert.deepEqual(result.entries.map(entry => entry.captured.understanding.status), labelFixtures[index].statuses);
        }
        assert.deepEqual(labelResult.removed, ['undefined', 'undefined', 'undefined']);
        const definitionFixtures = [];
        for (const [locale, forms] of Object.entries(wordCatalog.correctionTeaching)) {
            for (const foundation of [false, true]) for (const life of [false, true]) for (const speech of ['short', 'gesture']) {
                definitionFixtures.push({ values:[hearDefinition(makeNameState({ foundation, life, speech }), forms.exampleSource, locale)],
                    expected:[foundation && life] });
            }
        }
        const definitionText = wordCatalog.correctionTeaching.ja.exampleSource;
        const repeatedDefinitionState = makeNameState();
        definitionFixtures.push({ values:[hearDefinition(repeatedDefinitionState, definitionText),
            hearDefinition(repeatedDefinitionState, definitionText)], expected:[true, true] });
        assert.equal(repeatedDefinitionState.knowledge.wordExplanations.length, 1);
        assert.equal(repeatedDefinitionState.records.length, 1);
        const correctedDefinitionState = makeNameState();
        const originalDefinition = hearDefinition(correctedDefinitionState, definitionText);
        const correctedDefinition = hearDefinition(correctedDefinitionState, wordCatalog.correctionTeaching.ja.exampleReplacement);
        assert.ok(correctedDefinition.result.learning[0].retraction);
        definitionFixtures.push({ values:[originalDefinition, correctedDefinition], expected:[true, false] });
        const scopedDefinitionState = makeNameState(), firstDefinition = hearDefinition(scopedDefinitionState, definitionText);
        core.perceive(scopedDefinitionState, { scene:'shore', attention:[{ id:'berry:2', meaning:'berry' }] });
        const otherDefinition = hearDefinition(scopedDefinitionState, definitionText, 'ja', 'visitor');
        core.perceive(scopedDefinitionState, { scene:'shade', attention:[] });
        definitionFixtures.push({ values:[firstDefinition, otherDefinition, hearDefinition(scopedDefinitionState, definitionText)], expected:[true, true, true] });
        const appliedDefinitionState = makeNameState(); hearDefinition(appliedDefinitionState, definitionText);
        const appliedDefinition = hearDefinition(appliedDefinitionState, core.wordFrame(definitionText, 'ja').word);
        assert.equal(appliedDefinition.result.understandings[0].known.meaning, 'rest');
        definitionFixtures.push({ values:[appliedDefinition], expected:[false] });
        const missingDefinitionBasis = hearDefinition(makeNameState(), definitionText);
        missingDefinitionBasis.beforeKnowledge.meanings = [];
        definitionFixtures.push({ values:[missingDefinitionBasis], expected:[false] });
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_definitions.js'), 'utf8'));
        const definitionResult = await js(`(() => {
            const fixtures = ${JSON.stringify(definitionFixtures)};
            const results = fixtures.map(fixture => {
                const buffer = ExperimentalWordDiaryCandidates.create();
                const before = JSON.stringify(fixture.values);
                const capture = value => ExperimentalWordDiaryDefinitions.capture(buffer, value.result, value.context, value.beforeKnowledge);
                const accepted = fixture.values.map(capture), original = buffer.read();
                const repeated = fixture.values.map(capture);
                const untouched = JSON.stringify(fixture.values) === before;
                fixture.values[0].result.input.raw = 'later edit';
                if (original.length) buffer.read()[0].captured.basis.source = 'view edit';
                return { accepted, repeated, untouched, original, entries:buffer.read() };
            });
            delete globalThis.ExperimentalWordDiaryDefinitions;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { results, removed:[typeof ExperimentalWordDiaryDefinitions, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        for (const [index, result] of definitionResult.results.entries()) {
            assert.deepEqual(result.accepted, definitionFixtures[index].expected);
            assert.ok(result.repeated.every(value => value === false));
            assert.equal(result.untouched, true);
            assert.deepEqual(result.entries, result.original);
            const values = definitionFixtures[index].values.filter((_value, i) => definitionFixtures[index].expected[i]);
            assert.deepEqual(result.entries.map(entry => entry.sourceId), values.map(value => value.result.input.id));
            for (const [i, entry] of result.entries.entries()) {
                assert.equal(entry.kind, 'teaching');
                assert.deepEqual(entry.captured.sources.input, values[i].result.input);
                assert.deepEqual(entry.captured.sources.attention, values[i].context.attention);
                assert.deepEqual(entry.captured.understanding, values[i].result.understandings[0]);
                assert.deepEqual(entry.captured.basis, values[i].beforeKnowledge.meanings.find(item => item.id === entry.captured.understanding.known.meaning));
                assert.deepEqual(entry.captured.explanation, values[i].result.learning[0]);
            }
        }
        assert.deepEqual(definitionResult.removed, ['undefined', 'undefined']);
        const nameFixtures = [];
        for (const foundation of [false, true]) for (const life of [false, true]) for (const speech of ['short', 'gesture']) {
            nameFixtures.push({ values:[hearName(makeNameState({ foundation, life, speech }))], expected:[foundation] });
        }
        const repeatedNameState = makeNameState();
        nameFixtures.push({ values:[hearName(repeatedNameState), hearName(repeatedNameState)], expected:[true, true] });
        assert.equal(repeatedNameState.knowledge.associations[0].evidence.length, 1);
        assert.equal(repeatedNameState.records.length, 1);
        nameFixtures.push({ values:[hearName(makeNameState({}, [{ id:'berry:1', meaning:'berry' },
            { id:'berry:2', meaning:'berry' }]))], expected:[false] });
        nameFixtures.push({ values:[hearName(makeNameState(), '\u3053\u308d')], expected:[false] });
        nameFixtures.push({ values:[hearName(makeNameState(), '\u307d\u307d\u306f\u4f11\u3080\u3053\u3068\u3060\u3088')], expected:[false] });
        const correctedNameState = makeNameState(), originalName = hearName(correctedNameState);
        const correctedName = hearName(correctedNameState, '\u3055\u3063\u304d\u9593\u9055\u3048\u305f\u3002\u3053\u308d\u306f\u6728\u306e\u5b9f\u306e\u3053\u3068\u3060\u3088');
        assert.ok(correctedName.result.learning[0].retraction);
        nameFixtures.push({ values:[originalName, correctedName], expected:[true, false] });
        const differentNameState = makeNameState(), firstIndividual = hearName(differentNameState);
        core.perceive(differentNameState, { scene:'shore', attention:[{ id:'berry:2', meaning:'berry' }] });
        nameFixtures.push({ values:[firstIndividual, hearName(differentNameState)], expected:[true, true] });
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_names.js'), 'utf8'));
        const nameResult = await js(`(() => {
            const fixtures = ${JSON.stringify(nameFixtures)};
            const results = fixtures.map(fixture => {
                const buffer = ExperimentalWordDiaryCandidates.create();
                const before = JSON.stringify(fixture.values);
                const accepted = fixture.values.map(value => ExperimentalWordDiaryNames.capture(buffer, value.result, value.context));
                const original = buffer.read();
                const repeated = fixture.values.map(value => ExperimentalWordDiaryNames.capture(buffer, value.result, value.context));
                const untouched = JSON.stringify(fixture.values) === before;
                fixture.values[0].result.input.raw = 'later edit';
                if (original.length) buffer.read()[0].captured.sources.input.raw = 'view edit';
                return { accepted, repeated, untouched, original, entries:buffer.read() };
            });
            delete globalThis.ExperimentalWordDiaryNames;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { results, removed:[typeof ExperimentalWordDiaryNames, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        for (const [index, result] of nameResult.results.entries()) {
            assert.deepEqual(result.accepted, nameFixtures[index].expected);
            assert.ok(result.repeated.every(value => value === false));
            assert.equal(result.untouched, true);
            assert.deepEqual(result.entries, result.original);
            const accepted = nameFixtures[index].values.filter((_value, i) => nameFixtures[index].expected[i]);
            assert.deepEqual(result.entries.map(entry => entry.sourceId), accepted.map(value => value.result.input.id));
            for (const [i, entry] of result.entries.entries()) {
                assert.equal(entry.kind, 'teaching');
                assert.deepEqual(entry.captured.sources.input, accepted[i].result.input);
                assert.deepEqual(entry.captured.sources.attention, accepted[i].context.attention);
                assert.deepEqual(entry.captured.understanding, accepted[i].result.understandings[0]);
                assert.deepEqual(entry.captured.association, accepted[i].result.learning[0]);
            }
        }
        assert.deepEqual(nameResult.removed, ['undefined', 'undefined']);
        // Complete actual food/rest events in disposable Node state. Only their
        // before/after learning snapshots and the independent adapter enter the
        // renderer; this is not live diary generation or a player save test.
        const makeCompletion = (activity, labelled, options = {}) => {
            const state = core.create({ life:false, ...options }, wordCatalog), world = worldApi.create();
            Object.assign(world, { mode:activity, attention:activity === 'eat' ? 'berry:1' : 'shade',
                harvest:1, elapsed:1, activityStart:1, dwell:.1, hunger:.8, fatigue:.7,
                activityBefore:{ hunger:.8, fatigue:.7 } });
            if (activity === 'eat') world.mealTaste = { quality:'sweet', pleasant:true };
            if (labelled) for (const raw of activity === 'eat' ? ['eat', 'sweet', '"hungry"'] : ['rest', '"tired"']) {
                const result = core.receive(state, raw, wordCatalog, { locale:'en' });
                worldApi.respond(world, result, state);
                assert.ok(result.lifeLearning);
            }
            world.pause = 0;
            const event = worldApi.tick(world, .1), before = JSON.parse(JSON.stringify(state.knowledge));
            assert.equal(event.kind, 'experience');
            worldApi.onArrival(world, state, event);
            return { event, before, after:state.knowledge };
        };
        const completionFixtures = ['eat', 'rest'].flatMap(activity => [makeCompletion(activity, false),
            makeCompletion(activity, true), makeCompletion(activity, true, { life:true, speech:'gesture' })]);
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_experiences.js'), 'utf8'));
        const completionResult = await js(`(() => {
            const fixtures = ${JSON.stringify(completionFixtures)};
            const results = fixtures.map(value => {
                const buffer = ExperimentalWordDiaryCandidates.create();
                const source = JSON.stringify(value);
                const accepted = ExperimentalWordDiaryExperiences.capture(buffer, value.event, value.before, value.after);
                const original = buffer.read();
                value.after.meanings.push({ id:'unrelated', source:'initial' });
                const repeated = ExperimentalWordDiaryExperiences.capture(buffer, value.event, value.before, value.after);
                buffer.read()[0].captured.sensation.after.fatigue = 1;
                return { accepted, repeated, original, entries:buffer.read(),
                    sourcePreserved:source === JSON.stringify({ ...value,
                        after:{ ...value.after, meanings:value.after.meanings.filter(m=>m.id !== 'unrelated') } }) };
            });
            delete globalThis.ExperimentalWordDiaryExperiences;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { results, removed:[typeof ExperimentalWordDiaryExperiences, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        for (const [index, result] of completionResult.results.entries()) {
            assert.equal(result.accepted, true);
            assert.equal(result.repeated, false);
            assert.equal(result.sourcePreserved, true);
            assert.deepEqual(result.entries, result.original);
            const entry = result.entries[0], fixture = completionFixtures[index];
            assert.equal(entry.sourceId, fixture.event.id);
            assert.deepEqual(entry.captured.sensation.before, fixture.event.before);
            assert.deepEqual(entry.captured.sensation.after, fixture.event.after);
            assert.equal(entry.captured.understanding.recovery.status, index % 3 === 0 ? 'unrecognized' : 'recognized');
            if (index % 3 !== 0) assert.ok(entry.captured.understanding.recovery.known.every(item =>
                item.acquired === (index % 3 === 2 ? 'before_completion' : 'at_completion')));
            if (fixture.event.activity === 'eat') assert.deepEqual(entry.captured.sensation.taste, fixture.event.taste);
        }
        assert.deepEqual(completionResult.removed, ['undefined', 'undefined']);
        // Actual career starts/completions and learning in disposable Node
        // memory. The renderer receives only snapshots and independent parts.
        const careers = require('../../experimental_word_careers');
        const makeWorkCompletion = (master, demonstrated, state = core.create({ speech:'gesture' }, wordCatalog)) => {
            const world = worldApi.create();
            Object.assign(world, { mode:'observe', attention:`master:${master}`, elapsed:1, dwell:0,
                hunger:.1, fatigue:.1 });
            careers.arrive(world, { id:0, target:world.attention });
            world.careers.people[master].completed = (state.experiences || []).filter(e => e.master === master).length;
            world.dwell = 0;
            const start = careers.tick(world);
            assert.equal(start.kind, 'work_start');
            if (demonstrated) worldApi.onArrival(world, state, start);
            world.dwell = 0; world.elapsed = 20;
            world.event = Math.max(world.event, ...(state.experiences || []).map(e => e.id));
            const event = careers.tick(world), before = JSON.parse(JSON.stringify(state.knowledge));
            worldApi.onArrival(world, state, event);
            return { snapshot:{ event, before, after:JSON.parse(JSON.stringify(state.knowledge)) }, state };
        };
        const workFixtures = Object.keys(careers.JOBS).flatMap(master => {
            const fresh = makeWorkCompletion(master, true);
            return [makeWorkCompletion(master, false).snapshot, fresh.snapshot,
                makeWorkCompletion(master, true, fresh.state).snapshot];
        });
        const firstWork = makeWorkCompletion('farming', true);
        workFixtures.push(makeWorkCompletion('fishing', true, firstWork.state).snapshot);
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_candidates.js'), 'utf8'));
        await js(fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary_work.js'), 'utf8'));
        const workResult = await js(`(() => {
            const fixtures = ${JSON.stringify(workFixtures)};
            const results = fixtures.map(value => {
                const buffer = ExperimentalWordDiaryCandidates.create();
                const source = JSON.stringify(value);
                const accepted = ExperimentalWordDiaryWork.capture(buffer, value.event, value.before, value.after);
                const original = buffer.read();
                const sourcePreserved = source === JSON.stringify(value);
                value.after.meanings.push({ id:'unrelated', source:'initial' });
                const repeated = ExperimentalWordDiaryWork.capture(buffer, value.event, value.before, value.after);
                value.event.result = 'changed';
                buffer.read()[0].captured.sources.reasons[0].kind = 'changed';
                return { accepted, repeated, original, entries:buffer.read(), sourcePreserved };
            });
            delete globalThis.ExperimentalWordDiaryWork;
            delete globalThis.ExperimentalWordDiaryCandidates;
            return { results, removed:[typeof ExperimentalWordDiaryWork, typeof ExperimentalWordDiaryCandidates] };
        })()`);
        for (const [index, result] of workResult.results.entries()) {
            assert.equal(result.accepted, true);
            assert.equal(result.repeated, false);
            assert.equal(result.sourcePreserved, true);
            assert.deepEqual(result.entries, result.original);
            const entry = result.entries[0], fixture = workFixtures[index];
            assert.equal(entry.sourceId, fixture.event.id);
            assert.deepEqual(entry.captured.sources, { before:fixture.event.before, after:fixture.event.after,
                result:fixture.event.result, demonstration:fixture.event.demonstration, reasons:fixture.event.reasons });
            const u = entry.captured.understanding;
            assert.deepEqual(Object.keys(u), ['point', 'activity', 'task']);
            for (const aspect of ['activity', 'task']) {
                assert.equal(u[aspect].status, index < 18 && index % 3 === 0 ? 'unrecognized' : 'recognized');
                if (u[aspect].known.length) assert.equal(u[aspect].known[0].acquired,
                    index < 18 ? index % 3 === 2 ? 'before_completion' : 'at_completion'
                        : aspect === 'activity' ? 'before_completion' : 'at_completion');
            }
        }
        assert.deepEqual(workResult.removed, ['undefined', 'undefined']);
        const results = [];
        const originals = new Map();
        const source = fs.readFileSync(path.resolve(__dirname, '../../experimental_word_diary.js'), 'utf8');
        const fixtures = require('node:vm').runInNewContext(source.slice(source.indexOf('    const S ='), source.indexOf('    const root =')) + '\n({S, fixtures})');
        for (const width of [1000, 390]) {
            window.setContentSize(width, 900); await settle();
            for (const locale of ['ja', 'en', 'zh-CN', 'ru', 'es-ES', 'pt-BR', 'de']) {
                await js(`GameI18n.setLanguage(${JSON.stringify(locale)}); void 0`); await settle();
                for (const sample of ['berry', 'net', 'naming', 'heard', 'partial', 'long', 'selfRobot', 'selfDragon', 'meeting']) {
                    await js(`(() => { const select = document.querySelector('#diary-sample'); select.value = ${JSON.stringify(sample)}; select.dispatchEvent(new Event('change')); })()`);
                    await settle();
                    const data = await js(`(() => {
                        const pages = [...document.querySelectorAll('.diary-page')];
                        const text = pages.map(page => page.querySelector('.diary-text').textContent).join('');
                        let misaligned = false;
                        const overflow = pages.some(page => { const hidden = page.hidden; page.hidden = false;
                            const body = page.querySelector('.diary-text'); const bad = body.scrollWidth > body.clientWidth + 1 || body.scrollHeight > body.clientHeight + 1;
                            for (const sentence of body.querySelectorAll('.diary-sentence')) {
                                const textNode = sentence.firstChild;
                                const offset = textNode?.data.search(/\\S/u);
                                if (offset >= 0) {
                                    const range = document.createRange(); range.setStart(textNode, offset); range.setEnd(textNode, offset+1);
                                    if (Math.abs(range.getBoundingClientRect().top - body.getBoundingClientRect().top) > 4) misaligned = true;
                                }
                            }
                            page.hidden = hidden; return bad; });
                        const canvas = pages[0].querySelector('canvas');
                        const blank = !canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data.some((v,i) => i % 4 === 3 && v);
                        return { text, overflow, misaligned, blank, count:pages.length, canvases:document.querySelectorAll('canvas').length,
                            sentences:pages[0].querySelectorAll('.diary-sentence').length,
                            dates:pages.map(page => page.querySelector('.date').textContent),
                            mode:getComputedStyle(pages[0].querySelector('.diary-text')).writingMode,
                            font:getComputedStyle(pages[0].querySelector('.diary-text')).fontSize,
                            horizontal:document.documentElement.scrollWidth > innerWidth,
                            drawing:canvas.toDataURL(), title:document.title };
                    })()`);
                    assert.equal(data.overflow, false, `${width}/${locale}/${sample} text overflow`);
                    assert.equal(data.horizontal, false, `${width}/${locale}/${sample} viewport overflow`);
                    assert.equal(data.mode, ['ja', 'zh-CN'].includes(locale) ? 'vertical-rl' : 'horizontal-tb');
                    assert.equal(data.font, ['ja', 'zh-CN'].includes(locale) ? '18px' : '23px'); assert.equal(data.canvases, 1);
                    assert.equal(data.misaligned, false, 'each vertical sentence starts at the top of its column');
                    if (sample === 'berry' && ['ja', 'zh-CN'].includes(locale)) assert.equal(data.sentences, 3);
                    const doc = await window.webContents.debugger.sendCommand('DOM.getDocument');
                    const query = await window.webContents.debugger.sendCommand('DOM.querySelector', { nodeId:doc.root.nodeId, selector:'.diary-text' });
                    const platform = await window.webContents.debugger.sendCommand('CSS.getPlatformFontsForNode', { nodeId:query.nodeId });
                    assert.ok(platform.fonts.length && platform.fonts.every(font => font.isCustomFont), `bundled handwriting glyphs: ${locale} ${JSON.stringify(platform.fonts)}`);
                    const catalog = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../locales', locale + '.json'), 'utf8'));
                    const expected = fixtures.fixtures.find(item => item.id === sample).text.map(key => catalog[fixtures.S[key]]).join('\n\n');
                    const day = fixtures.fixtures.find(item => item.id === sample).day;
                    const month = ['ja','zh-CN'].includes(locale) ? 4 : new Intl.DateTimeFormat(locale,{month:'long',day:'numeric',timeZone:'UTC'}).formatToParts(new Date(Date.UTC(2000,3,day))).find(part=>part.type==='month').value;
                    const dateText = key => catalog[fixtures.S[key]].replace(/\{\{(\d+)\}\}/g, (_, i) => [month,day][i]);
                    assert.deepEqual(data.dates, data.dates.map((_,i)=>dateText(i ? 'continued':'day')), 'same sample month and day on continuations');
                    assert.equal(data.text, expected, 'every authored translated character remains, in order');
                    assert.equal(data.blank, ['heard', 'partial'].includes(sample));
                    if (sample === 'long') assert.ok(data.count > 1);
                    const key = locale + '/' + sample;
                    if (originals.has(key)) assert.deepEqual([data.text, data.drawing], originals.get(key), 'reflow preserves every character and drawing');
                    else originals.set(key, [data.text, data.drawing]);
                    if (!['ja', 'zh-CN'].includes(locale)) assert.equal(/[\u3040-\u30ff]/.test(data.text + data.title), false);
                    // Real hit-tested mouse input forward, DOM input backward through every continuation.
                    for (let i = 1; i < data.count; i++) {
                        await js(`document.querySelector('#diary-next').scrollIntoView({block:'center'}); void 0`);
                        await settle();
                        const visiblePoint = await js(`(() => { const r=document.querySelector('#diary-next').getBoundingClientRect(); return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}; })()`);
                        window.webContents.sendInputEvent({ type:'mouseMove', ...visiblePoint });
                        await settle();
                        window.webContents.sendInputEvent({ type:'mouseDown', ...visiblePoint, button:'left', clickCount:1 });
                        await js('new Promise(resolve => setTimeout(resolve, 30))');
                        window.webContents.sendInputEvent({ type:'mouseUp', ...visiblePoint, button:'left', clickCount:1 });
                        await settle();
                        assert.equal(await js(`[...document.querySelectorAll('.diary-page')].findIndex(p=>!p.hidden)`), i, `${width}/${locale}/${sample}: mouse page ${i}`);
                    }
                    for (let i = data.count - 2; i >= 0; i--) {
                        await js(`document.querySelector('#diary-previous').click(); void 0`);
                        assert.equal(await js(`[...document.querySelectorAll('.diary-page')].findIndex(p=>!p.hidden)`), i);
                    }
                    results.push({ width, locale, sample, pages:data.count });
                    if ((width === 1000 && ['ja','ru','en'].includes(locale) && ['berry','net','long','selfRobot','selfDragon','meeting'].includes(sample)) || (width === 390 && ['zh-CN','de'].includes(locale) && sample === 'long')) {
                        await js('scrollTo(0,0); void 0');
                        await settle();
                        await window.webContents.capturePage(); await settle();
                        fs.writeFileSync(path.join(directory, `${width}-${locale}-${sample}.png`), (await window.webContents.capturePage()).toPNG());
                        if (sample === 'long') {
                            await js(`document.querySelector('#diary-next').click(); document.querySelector('.book').scrollIntoView({block:'start'}); void 0`);
                            await settle();
                            fs.writeFileSync(path.join(directory, `${width}-${locale}-${sample}-continued.png`), (await window.webContents.capturePage()).toPNG());
                        }
                    }
                }
            }
        }
        assert.deepEqual(await js(`({local:{...localStorage},session:{...sessionStorage},world:typeof ExperimentalWordWorld,legacy:typeof aiPet,bridge:typeof wordLifeStorage})`),
            { local:{'preview-sentinel':'keep'}, session:{'preview-sentinel':'keep'}, world:'undefined',legacy:'undefined',bridge:'undefined' });
        await window.reload(); await settle();
        assert.equal(await js('GameI18n.language'), 'ja', 'sample language is not saved');
        assert.equal(await js(`document.querySelector('#diary-sample').value`), 'berry');
        assert.deepEqual(errors, []);
        fs.writeFileSync(path.join(directory, 'results.json'), JSON.stringify(results, null, 2));
        console.log(JSON.stringify({ ok:true, cases:results.length, clockCases:7, candidateChecks:6, questionChecks:7,
            completionCases:completionResult.results.length, workCompletionCases:workResult.results.length,
            nameCases:nameResult.results.length, nameInputs:nameFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0),
            definitionCases:definitionResult.results.length, definitionInputs:definitionFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0),
            lifeLabelCases:labelResult.results.length, lifeLabelInputs:labelFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0),
            relationLabelCases:relationResult.results.length, relationLabelInputs:relationFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0),
            questionExampleCases:exampleResult.results.length, questionExampleInputs:exampleFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0),
            knownQuestionExampleCases:knownExampleResult.results.length, knownQuestionExampleInputs:knownExampleFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0),
            proposalExampleCases:proposalResult.results.length, proposalExampleInputs:proposalFixtures.reduce((sum, fixture) => sum + fixture.values.length, 0), profile:directory })); app.quit();
    }).catch(error => { console.error(error); app.exit(1); });
    app.on('window-all-closed', () => app.quit());
    app.on('before-quit', () => { if (server) { server.closeAllConnections(); server.close(); } });
}
