'use strict';
const fs = require('node:fs');
const path = require('node:path');
const rows = [
 ['日記帳の見た目・独立見本', 'Diary appearance · independent sample', '日记外观·独立示例', 'Внешний вид дневника · отдельный образец', 'Aspecto del diario · muestra independiente', 'Visual do diário · amostra independente', 'Tagebuchgestaltung · unabhängiges Muster'],
 ['これは外観だけの見本です。本人の記録・経験・知識・保存とはつながっていません。見本の切替は、本人の絵を選ぶ操作ではありません。', 'This is an appearance sample only. It is separate from the character’s records, experiences, knowledge and saves. Switching samples does not choose the character’s drawing.', '这只是外观示例，与角色的记录、经历、知识和存档无关。切换示例并不是替角色选择画作。', 'Это только образец оформления. Он не связан с записями, опытом, знаниями и сохранениями персонажа. Переключение образцов не выбирает его рисунок.', 'Esta muestra solo presenta el aspecto visual. Es independiente de los registros, experiencias, conocimientos y partidas guardadas del personaje. Cambiar de muestra no elige su dibujo.', 'Esta amostra mostra apenas o visual. Ela é independente dos registros, experiências, conhecimentos e dados salvos do personagem. Trocar a amostra não escolhe o desenho dele.', 'Dies ist nur ein Gestaltungsmuster. Es ist unabhängig von Aufzeichnungen, Erfahrungen, Wissen und Spielständen der Figur. Ein Musterwechsel wählt nicht ihre Zeichnung aus.'],
 ['見本の表示言語', 'Sample language', '示例语言', 'Язык образца', 'Idioma de la muestra', 'Idioma da amostra', 'Sprache des Musters'],
 ['表示する見本ページ', 'Sample pages to view', '要查看的示例页面', 'Страницы образца для просмотра', 'Páginas de muestra', 'Páginas de amostra', 'Anzuzeigende Musterseiten'],
 ['見本：木の実を食べた日', 'Sample: a day of eating berries', '示例：吃浆果的一天', 'Образец: день, когда пробовали ягоды', 'Muestra: un día comiendo bayas', 'Amostra: um dia comendo frutas', 'Muster: ein Tag mit Beeren'],
 ['見本：網の結び目がほどけた日', 'Sample: a day the net knot came undone', '示例：网结松开的一天', 'Образец: день, когда узел сети развязался', 'Muestra: el día que se deshizo el nudo', 'Amostra: o dia em que o nó da rede se soltou', 'Muster: der Tag, an dem sich der Netzknoten löste'],
 ['見本：実を見ながら名前を教わった日', 'Sample: learning a name while looking at a berry', '示例：看着果实学名称的一天', 'Образец: узнаём название, глядя на ягоду', 'Muestra: aprender un nombre mirando una baya', 'Amostra: aprender um nome olhando uma fruta', 'Muster: einen Namen beim Betrachten einer Beere lernen'],
 ['見本：話を聞いた日（絵なし）', 'Sample: a day of listening (no drawing)', '示例：听讲的一天（无画作）', 'Образец: день беседы (без рисунка)', 'Muestra: un día escuchando (sin dibujo)', 'Amostra: um dia ouvindo (sem desenho)', 'Muster: ein Tag des Zuhörens (ohne Zeichnung)'],
 ['見本：まだ一日の途中（絵なし）', 'Sample: a day still in progress (no drawing)', '示例：一天尚未结束（无画作）', 'Образец: день ещё идёт (без рисунка)', 'Muestra: un día en curso (sin dibujo)', 'Amostra: um dia ainda em andamento (sem desenho)', 'Muster: ein laufender Tag (ohne Zeichnung)'],
 ['見本：長い日の続きページ', 'Sample: continuation pages for a long day', '示例：长篇日记的续页', 'Образец: продолжение длинной записи', 'Muestra: continuación de un día largo', 'Amostra: continuação de um dia longo', 'Muster: Folgeseiten eines langen Tages'],
 ['見本の一日 {{0}}', 'Sample day {{0}}', '示例第 {{0}} 天', 'День образца {{0}}', 'Día de muestra {{0}}', 'Dia de amostra {{0}}', 'Mustertag {{0}}'],
 ['見本の一日 {{0}}・続き', 'Sample day {{0}} · continued', '示例第 {{0}} 天·续页', 'День образца {{0}} · продолжение', 'Día de muestra {{0}} · continuación', 'Dia de amostra {{0}} · continuação', 'Mustertag {{0}} · Fortsetzung'],
 ['{{0}} / {{1}} ページ', 'Page {{0}} / {{1}}', '第 {{0}} / {{1}} 页', 'Страница {{0}} / {{1}}', 'Página {{0}} / {{1}}', 'Página {{0}} / {{1}}', 'Seite {{0}} / {{1}}'],
 ['前の見本ページ', 'Previous sample page', '上一示例页', 'Предыдущая страница', 'Muestra anterior', 'Amostra anterior', 'Vorherige Musterseite'],
 ['次の見本ページ', 'Next sample page', '下一示例页', 'Следующая страница', 'Muestra siguiente', 'Próxima amostra', 'Nächste Musterseite'],
 ['一日の途中の見本。絵の場所は、まだ空欄です。', 'Sample of a day in progress. The drawing area is still blank.', '一天尚未结束的示例。画作区域仍为空白。', 'Образец незавершённого дня. Место для рисунка пока пустое.', 'Muestra de un día en curso. El espacio del dibujo sigue vacío.', 'Amostra de um dia em andamento. O espaço do desenho ainda está vazio.', 'Muster eines laufenden Tages. Der Platz für die Zeichnung ist noch leer.'],
 ['絵の候補がない日の見本。本文だけを残します。', 'Sample of a day with no drawing candidate. Only the text remains.', '没有可画题材的一天的示例。只保留正文。', 'Образец дня без темы для рисунка. Остаётся только текст.', 'Muestra de un día sin tema para dibujar. Solo queda el texto.', 'Amostra de um dia sem tema para desenhar. Fica apenas o texto.', 'Muster eines Tages ohne Zeichnungskandidaten. Nur der Text bleibt.'],
 ['素朴な絵の見本：{{0}}', 'Simple drawing sample: {{0}}', '朴素画作示例：{{0}}', 'Образец простого рисунка: {{0}}', 'Muestra de dibujo sencillo: {{0}}', 'Amostra de desenho simples: {{0}}', 'Muster einer einfachen Zeichnung: {{0}}'],
 ['共通の描線と紙面は暫定です。日付時計・本文の採用・印象の比較・本人の絵の選択・保存は未接続です。', 'The shared drawing style and page layout are provisional. The day clock, text selection, impression comparison, character’s drawing choice and saving are not connected.', '共通线条与页面布局为暂定方案。日期时钟、正文选取、印象比较、角色自主选画和保存尚未连接。', 'Общий стиль линий и оформление пока пробные. Часы дня, отбор текста, сравнение впечатлений, выбор рисунка персонажем и сохранение не подключены.', 'El trazo común y el diseño son provisionales. El reloj, la selección del texto, la comparación de impresiones, la elección del dibujo por el personaje y el guardado no están conectados.', 'O traço comum e o layout são provisórios. O relógio, a seleção do texto, a comparação de impressões, a escolha do desenho pelo personagem e o salvamento não estão conectados.', 'Der gemeinsame Zeichenstil und die Seitengestaltung sind vorläufig. Tagesuhr, Textauswahl, Eindrucksvergleich, Zeichnungswahl der Figur und Speichern sind nicht angeschlossen.'],
 ['赤い実を見つけた。食べると甘かった。もう一つ食べた実は、少しすっぱかった。', 'I found a red berry. It tasted sweet. Another berry I ate was a little sour.', '发现了红色的果实。吃起来很甜。又吃了一颗，有点酸。', 'Нашлась красная ягода. На вкус она была сладкой. Другая съеденная ягода была немного кислой.', 'Encontré una baya roja. Sabía dulce. Otra que comí era un poco ácida.', 'Encontrei uma fruta vermelha. Ela era doce. Outra que comi era um pouco azeda.', 'Ich fand eine rote Beere. Sie schmeckte süß. Eine andere Beere war etwas sauer.'],
 ['網の結び目をまねしてみた。引っぱると、ほどけた。どこが違ったのか、まだ分からない。', 'I tried copying the net knot. It came undone when I pulled. I still do not know what was different.', '试着模仿网结。一拉就松开了。还不知道哪里不一样。', 'Я попробовал повторить узел сети. Он развязался, когда я потянул. Пока не знаю, что было иначе.', 'Intenté copiar el nudo de la red. Se deshizo al tirar. Aún no sé qué era diferente.', 'Tentei copiar o nó da rede. Ele se soltou quando puxei. Ainda não sei o que ficou diferente.', 'Ich versuchte, den Netzknoten nachzumachen. Beim Ziehen löste er sich. Ich weiß noch nicht, was anders war.'],
 ['目の前の赤い実を「木の実」と教わった。この実を指す名前は教わったけれど、ほかの実も同じ名前なのかは、まだ確かめていない。', 'I was taught to call the red fruit in front of me a “berry.” I learned its name, but have not checked whether other fruit has the same name.', '有人教我把眼前的红色果实叫作“浆果”。学会了这颗果实的名称，但还没确认其他果实是不是也叫这个名字。', 'Мне сказали, что красный плод передо мной называется «ягода». Я узнал название этого плода, но ещё не проверил, так ли называются другие.', 'Me enseñaron que el fruto rojo que tenía delante se llama «baya». Aprendí su nombre, pero no he comprobado si otros frutos se llaman igual.', 'Me ensinaram a chamar a fruta vermelha à minha frente de “fruta silvestre”. Aprendi seu nome, mas ainda não verifiquei se outras frutas têm o mesmo nome.', 'Die rote Frucht vor mir wurde mir als „Beere“ benannt. Ich lernte ihren Namen, habe aber noch nicht geprüft, ob andere Früchte genauso heißen.'],
 ['師匠が、網の結び目について話してくれた。話は聞いたけれど、今日は網を見たり、結んだりしていない。', 'The mentor told me about net knots. I listened, but did not see or tie a net today.', '师傅给我讲了网结。听了讲解，但今天没有看网，也没有打结。', 'Наставник рассказал об узлах сети. Я слушал, но сегодня не видел сеть и не вязал узлы.', 'Mi mentor me habló de los nudos de la red. Escuché, pero hoy no vi ni até una red.', 'O mestre me falou sobre os nós da rede. Eu ouvi, mas hoje não vi nem amarrei uma rede.', 'Mein Meister erzählte von Netzknoten. Ich hörte zu, habe heute aber kein Netz gesehen oder geknüpft.'],
 ['実を見つけた。名前を教わった。味は、まだ確かめていない。', 'I found a berry. I learned its name. I have not checked its taste yet.', '发现了果实。学了名称。还没有尝过味道。', 'Нашлась ягода. Я узнал её название. Вкус пока не проверил.', 'Encontré una baya. Aprendí su nombre. Aún no he probado su sabor.', 'Encontrei uma fruta. Aprendi seu nome. Ainda não provei seu sabor.', 'Ich fand eine Beere. Ich lernte ihren Namen. Den Geschmack habe ich noch nicht geprüft.'],
 ['朝、赤い実を見つけた。近くで見ると、小さな点があった。', 'In the morning I found a red berry. Up close, it had little dots.', '早上发现了红色果实。凑近看，上面有小点。', 'Утром нашлась красная ягода. Вблизи на ней были маленькие точки.', 'Por la mañana encontré una baya roja. De cerca tenía puntitos.', 'De manhã encontrei uma fruta vermelha. De perto, ela tinha pontinhos.', 'Am Morgen fand ich eine rote Beere. Aus der Nähe hatte sie kleine Punkte.'],
 ['実を見ながら名前を教わった。ほかの実にも使える名前なのかは、まだ分からない。', 'I learned its name while looking at it. I do not yet know whether that name also fits other berries.', '看着果实学了名称。还不知道其他果实是否也能用这个名字。', 'Я узнал название, глядя на ягоду. Пока не знаю, подходит ли оно другим ягодам.', 'Aprendí su nombre mirándola. Aún no sé si ese nombre sirve para otras bayas.', 'Aprendi seu nome olhando para ela. Ainda não sei se esse nome serve para outras frutas.', 'Ich lernte den Namen, während ich sie betrachtete. Ich weiß noch nicht, ob er auch für andere Beeren passt.'],
 ['一つ食べた。甘かった。次の実は少しすっぱかった。同じ色でも、味は少し違った。', 'I ate one. It was sweet. The next berry was a little sour. The color was the same, but the taste differed a little.', '吃了一颗。很甜。下一颗有点酸。颜色一样，味道却有点不同。', 'Я съел одну. Она была сладкой. Следующая оказалась немного кислой. Цвет одинаковый, а вкус немного разный.', 'Comí una. Era dulce. La siguiente era algo ácida. Tenían el mismo color, pero sabores algo distintos.', 'Comi uma. Era doce. A próxima era um pouco azeda. A cor era igual, mas o sabor era um pouco diferente.', 'Ich aß eine. Sie war süß. Die nächste war etwas sauer. Gleiche Farbe, aber etwas anderer Geschmack.'],
 ['網の結び目を見た。まねして結ぶと、引っぱったときにほどけた。もう一度、師匠の手元を見た。', 'I watched a net knot. I copied it, but it came undone when I pulled. I watched the mentor’s hands again.', '看了网结。模仿着打结，一拉就松开了。又看了一次师傅的手。', 'Я смотрел на узел сети. Повторил его, но при натяжении он развязался. Я снова посмотрел на руки наставника.', 'Miré un nudo de la red. Lo copié, pero se deshizo al tirar. Volví a mirar las manos de mi mentor.', 'Observei um nó da rede. Copiei, mas ele se soltou quando puxei. Olhei de novo as mãos do mestre.', 'Ich betrachtete einen Netzknoten. Ich machte ihn nach, aber beim Ziehen löste er sich. Ich schaute noch einmal auf die Hände meines Meisters.'],
 ['もう一度結んだ。今度は引っぱっても、ほどけなかった。最初に結んだものとの違いは、まだうまく説明できない。', 'I tied it again. This time it stayed tied when I pulled. I cannot yet explain well how it differs from my first knot.', '又打了一次结。这次拉了也没有松开。还说不清和第一次的结有什么不同。', 'Я завязал снова. На этот раз при натяжении узел не развязался. Пока не могу хорошо объяснить отличие от первого.', 'Lo até de nuevo. Esta vez no se deshizo al tirar. Aún no puedo explicar bien la diferencia con el primero.', 'Amarrei de novo. Desta vez não se soltou quando puxei. Ainda não consigo explicar bem a diferença do primeiro nó.', 'Ich knüpfte noch einmal. Diesmal hielt der Knoten beim Ziehen. Den Unterschied zum ersten kann ich noch nicht gut erklären.'],
 ['夕方、朝の実をもう一度見た。食べていない実の味は分からない。今日、確かめたことをここに残しておく。', 'In the evening I looked again at the morning’s berries. I do not know the taste of berries I have not eaten. I leave what I checked today here.', '傍晚又看了早上的果实。没吃过的果实，不知道味道。把今天确认过的事情留在这里。', 'Вечером я снова посмотрел на утренние ягоды. Вкус несъеденных ягод мне неизвестен. Оставлю здесь то, что проверил сегодня.', 'Por la tarde volví a mirar las bayas de la mañana. No sé el sabor de las que no he comido. Dejo aquí lo que comprobé hoy.', 'À tarde olhei de novo as frutas da manhã. Não sei o sabor das que não comi. Deixo aqui o que verifiquei hoje.', 'Am Abend betrachtete ich die Beeren vom Morgen noch einmal. Den Geschmack ungegessener Beeren kenne ich nicht. Ich halte hier fest, was ich heute geprüft habe.']
];
for (const [index, locale] of ['ja', 'en', 'zh-CN', 'ru', 'es-ES', 'pt-BR', 'de'].entries()) {
    const file = path.resolve(__dirname, '../../locales', locale + '.json');
    const catalog = JSON.parse(fs.readFileSync(file, 'utf8'));
    for (const row of rows) catalog[row[0]] = row[index];
    fs.writeFileSync(file, JSON.stringify(catalog, null, 2) + '\n', 'utf8');
}
